#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ColorViewer.Resource", IsApplication=true)]

namespace ColorViewer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000c
			public const int buttonEditText = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int buttonSliders = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int colorDisplay = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int editTextBlue = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int editTextGreen = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int editTextRed = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int layoutSliders = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int seekBarBlue = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int seekBarGreen = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int seekBarRed = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int textBlue = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int textGreen = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int textRed = 2130968581;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ColorEditText = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ColorSliders = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
